name: 'Build Test Deploy'
description: 'Builds, Test and Deploys Maven Project'
inputs:
  artifactoryUser:
    description: 'Username for Artifactory - Needs Write Permission'
    required: true
  artifactoryPassword:
    description: 'Password for Artifactory - Needs Write permission'
    required: true

runs:
  using: "composite"
  steps:
  # Build project
  - name: Build with Maven
    run: mvn -B package -P cicd
    shell: bash
    env:
      ARTIFACTORY_USERNAME: "${{ inputs.artifactoryUser }}"
      ARTIFACTORY_PASSWORD: "${{ inputs.artifactoryPassword }}"
