name: 'Set up Maven'
description: 'Set up Maven xml'

runs:
  using: "composite"
  steps:

  # At the moment, Telia runners doesn't have Maven installed. This might change in the future.
  - name: Install Maven
    run: sudo apt update && sudo apt install maven -y
    shell: bash

  # Step that does that actual cache save and restore
  - name: Cache local Maven repository
    uses: actions/cache@v2
    with:
      path: ~/.m2
      key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      restore-keys: |
        ${{ runner.os }}-maven-
  - name: Set up Maven
    uses: telia-actions/generate-maven-settings@v17
    with:
      servers: |
          [
          {
              "id": "all-mirror",
              "username": "${env.ARTIFACTORY_USERNAME}",
              "password": "${env.ARTIFACTORY_PASSWORD}"
          },
          {
              "id": "snapshots",
              "username": "${env.ARTIFACTORY_USERNAME}",
              "password": "${env.ARTIFACTORY_PASSWORD}"
          },
          {
              "id": "releases",
              "username": "${env.ARTIFACTORY_USERNAME}",
              "password": "${env.ARTIFACTORY_PASSWORD}"
          },
          {
              "id": "plugins",
              "username": "${env.ARTIFACTORY_USERNAME}",
              "password": "${env.ARTIFACTORY_PASSWORD}"
          }
          ]
